
//declare an array to store the images 
var randomImage = new Array(); 

//insert the URL of images in array  
randomImage[0] = "Babel by R.F. Kuang";  
randomImage[1] = "Everywhere With You by Carlie Sorosiak";  
randomImage[2] = "Honey and Spice by Bolu Babalola";  
randomImage[3] = "An Immense World by Ed Yong";  
randomImage[4] = "In Love by Amy Bloom";  
randomImage[5] = "Lolo's Light by Liz Garton Scanlon";  
randomImage[6] = "Man o' War by Cory McCarthy"; 
randomImage[7] = "The Rabbit Hutch by Tess Gunty"; 
randomImage[8] = "Winter Work by Dan Fesperman"; 
randomImage[9] = "Trust by Hernan Diaz";


function getRandomImage() { 
   
    //generate a number and provide to the image to generate randomly  
    var number = Math.floor(Math.random()*randomImage.length);  
      
    //return the images generated by a random number 
    
    return document.getElementById("randomTitle").innerHTML = randomImage[number];
    
    }